-- CITY
CREATE TABLE S24_S003_T6_CITY (
  CID VARCHAR2(20) NOT NULL CONSTRAINT CID PRIMARY KEY,
  NAME VARCHAR2(20) NOT NULL,
  STATE VARCHAR2(20) NOT NULL,
  ZIP VARCHAR2(20) NOT NULL
);

-- ROUTE
CREATE TABLE S24_S003_T6_ROUTE (
  RID VARCHAR2(20) NOT NULL CONSTRAINT RID PRIMARY KEY,
  SOURCE_CID VARCHAR2(20) CONSTRAINT SOURCE_CID REFERENCES S24_S003_T6_CITY(CID),
  DEST_CID VARCHAR2(20) CONSTRAINT DEST_CID REFERENCES S24_S003_T6_CITY(CID)
);


-- BUS
CREATE TABLE S24_S003_T6_BUS (
    BNUMBER VARCHAR(20) NOT NULL CONSTRAINT BNUMBER PRIMARY KEY,
    TYPE VARCHAR(20)
);

-- DRIVER
CREATE TABLE S24_S003_T6_DRIVER (
  DID VARCHAR(20) CONSTRAINT DID PRIMARY KEY, 
  License VARCHAR2(20) NOT NULL CONSTRAINT Unique_Licence UNIQUE,
  DOB VARCHAR2(20),
  NAME VARCHAR2(50) NOT NULL,
  EMAIL VARCHAR(50) NOT NULL
);

-- BUS ASSIGNED
CREATE TABLE S24_S003_T6_BUS_ASSIGNED (
    BNUMBER VARCHAR2(20) CONSTRAINT BUS_ASSIGNED_FK REFERENCES S24_S003_T6_BUS(BNUMBER),
    DID VARCHAR2(20) CONSTRAINT DRIVER_ASSIGNED_FK REFERENCES S24_S003_T6_DRIVER(DID)
);


 -- DRIVER_PHONE
CREATE TABLE S24_S003_T6_DRIVER_PHONE (
PHONE_NO VARCHAR2(20),
DID VARCHAR(20) CONSTRAINT DRIVER_PHONE_DID REFERENCES S24_S003_T6_DRIVER(DID));

-- PASSENGER
CREATE TABLE S24_S003_T6_PASSENGER (
PID VARCHAR2(20) CONSTRAINT PID PRIMARY KEY,  
NAME VARCHAR2(20) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
PASSWORD VARCHAR(50) NOT NULL,
USERNAME VARCHAR2(50) NOT NULL CONSTRAINT UNIQUE_USERNAME UNIQUE,
CITY VARCHAR2(20) NOT NULL,
ZIP VARCHAR2(20) NOT NULL,
STREET VARCHAR2(20) NOT NULL,
STATE VARCHAR2(20) NOT NULL,
APT_NO VARCHAR2(20) NOT NULL,
DOB VARCHAR2(20)
);

-- PASSENGER_PHONE
CREATE TABLE S24_S003_T6_PASSENGER_PHONE (
PHONE_NO VARCHAR2(20),
PID VARCHAR2(20) CONSTRAINT PASSENGER_PHONE_DID REFERENCES S24_S003_T6_PASSENGER(PID));

-- Ticket
CREATE TABLE S24_S003_T6_TICKET (
  TID VARCHAR(20) NOT NULL CONSTRAINT TID PRIMARY KEY,
  TDATE DATE NOT NULL,
  TTIME VARCHAR(20) NOT NULL,
  PRICE NUMBER NOT NULL,
  BDATE DATE NOT NULL,
  BTIME VARCHAR(20) NOT NULL,
  NO_OF_SEATS NUMBER NOT NULL,
  BNUMBER VARCHAR(20) CONSTRAINT TICKET_BNUMBER_FK REFERENCES S24_S003_T6_BUS(BNUMBER),
  PID VARCHAR(20) CONSTRAINT TICKET_PASSENGER_FK REFERENCES S24_S003_T6_PASSENGER(PID),
  RID VARCHAR(20) CONSTRAINT TICKET_ROUTE_FK REFERENCES S24_S003_T6_ROUTE(RID)
);
